### ISSUE TITLE
Letsencrypt met Nginx

### ISSUE THREAD

**Issue by SandroNeumann** [IDgis/kennisbank#25]
Voeg de volgende volumes aan de nginx-proxy container toe:
```
 base_certs:/etc/nginx/certs:ro
 base_vhost:/etc/nginx/vhost.d
 base_html:/usr/share/nginx/html
```
Voeg de letsencrypt container toe:
```
nginx-letsencrypt:
  restart: always
  image: jrcs/letsencrypt-nginx-proxy-companion
  volumes_from:
    - nginx-proxy
  volumes:
    - base_certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
```
Voeg aan de applicatie de volgende omgevingsvariabelen toe:
```
LETSENCRYPT_HOST=[zelfde waarde als virtual_host]
LETSENCRYPT_EMAIL=[emailadres, verplicht om in te vullen]
```
